// AUTO-GENERATED by generate-textures.js — do not edit by hand.
// Re-run "node generate-textures.js" after adding/removing texture folders.
export const generatedTextures = [
  {
    "id": "concrete024_2k_jpg",
    "label": "Concrete 024",
    "textureFolder": "Concrete024_2K-JPG"
  },
  {
    "id": "fabric039_2k_jpg",
    "label": "Fabric 039",
    "textureFolder": "Fabric039_2K-JPG"
  },
  {
    "id": "fabric062_2k_jpg",
    "label": "Fabric 062",
    "textureFolder": "Fabric062_2K-JPG"
  },
  {
    "id": "tiles138_2k_jpg",
    "label": "Tiles 138",
    "textureFolder": "Tiles138_2K-JPG"
  },
  {
    "id": "tiles141_2k_jpg",
    "label": "Tiles 141",
    "textureFolder": "Tiles141_2K-JPG"
  },
  {
    "id": "tiles142_2k_jpg",
    "label": "Tiles 142",
    "textureFolder": "Tiles142_2K-JPG"
  },
  {
    "id": "wood051_2k_jpg",
    "label": "Wood 051",
    "textureFolder": "Wood051_2K-JPG"
  },
  {
    "id": "wood083a_2k_jpg",
    "label": "Wood 083A",
    "textureFolder": "Wood083A_2K-JPG"
  },
  {
    "id": "wood092_2k_jpg",
    "label": "Wood 092",
    "textureFolder": "Wood092_2K-JPG"
  },
  {
    "id": "wood095_2k_jpg",
    "label": "Wood 095",
    "textureFolder": "Wood095_2K-JPG"
  },
  {
    "id": "woodfloor007_2k_jpg",
    "label": "Wood Floor 007",
    "textureFolder": "WoodFloor007_2K-JPG"
  }
];
